version: "3.8"

services:
  api:
    build: .
    container_name: documind_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: pgvector/pgvector:pg15
    container_name: documind_db
    environment:
      POSTGRES_DB: documind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7
    container_name: documind_redis

  worker:
    build: .
    command: python -m app.workers.query_worker
    depends_on:
      - db
      - redis
    env_file:
      - .env